#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/patroni-pgbackrest
pgbackrest_user: postgres  # pgbackrest运行用户，保持和patroni里运行postgres用户一致,默认是postgres
pgbackrest_backup_pgpass: "postgres" # postgres管理员用户的密码，保持和patroni里postgres管理员用户密码一致
pgbackrest_socket_dir: /tmp # pgbouncer代理socket目录
pgbackrest_pg_port: 5433  # pgbouncer代理端口，采用方案是postgres的sidecar模式
pgbackrest_home: /var/lib/postgresql
pgbackrest_backup_dir: /patroni_backup
pgbackrest_backup_log_dir: /patroni_log
pgbackrest_backup_server: pg-backup # 指定备份服务器
pgbackrest_stanza: ha  # 备份仓库名称

# 注意：pgbackrest 通过 ssh 在备份服务器与 patroni 节点之间通信，
# 对应的 ssh 密钥对应在 group_vars/<group>/pg_all.yaml 中配置（pgbackrest_ssh_private_key / pgbackrest_ssh_public_key）

pgbackrest_backup_config: |    # 备份服务器的pgbackrest配置
  [global]
  repo1-path={{ pgbackrest_backup_dir }}
  repo1-retention-full=7
  repo1-retention-full-type=time

  process-max=2
  archive-check=y
  start-fast=y

  log-level-console=info
  log-path={{ pgbackrest_backup_log_dir }}
  log-level-file=debug

  [{{ pgbackrest_stanza }}]
  pg1-host=127.0.0.1
  pg1-host-port=22
  pg1-host-user=postgres
  pg1-path=/srv/patroni/postgres/data
  pg1-port={{ pgbackrest_pg_port }}
  pg1-socket-path={{ pgbackrest_socket_dir }}
  pg1-database=postgres

pgbackrest_patroni_config: | # patroni节点的pgbackrest配置
  [global]
  repo1-path={{ pgbackrest_backup_dir }}
  repo1-retention-full=7
  repo1-retention-full-type=time

  repo1-host=127.0.0.1
  repo1-host-port=22
  repo1-host-user=postgres

  process-max=2
  archive-check=y
  start-fast=y

  log-level-console=info
  log-path={{ pgbackrest_backup_log_dir }}
  log-level-file=debug

  [{{ pgbackrest_stanza }}]
  pg1-path=/srv/patroni/postgres/data
  pg1-port={{ pgbackrest_pg_port }}
  pg1-socket-path={{ pgbackrest_socket_dir }}
  pg1-database=postgres
