---

- name: restart supervisor
  service:
    name: supervisor
    state: restarted
  when: supervisor_do_restart | bool

- name: update supervisor
  shell: supervisorctl update
  when: supervisor_do_restart | bool

- name: reread supervisor
  shell: supervisorctl reread
  notify: update supervisor
