[general]
host = "{{ pgdog_host }}"
port = {{ item.port }}
workers = 2
default_pool_size = 10
pooler_mode = "transaction"
openmetrics_port = {{ item.openmetrics_port | default(pgdog_openmetrics_port) }}

{% for db in item.databases %}
[[databases]]
name = "{{ db.name }}"
host = "{{ db.host }}"
port = {{ db.port }}
database_name = "{{ db.database_name }}"
shard = {{ db.shard }}
{% if db.role is defined %}
role = "{{ db.role }}"
{% endif %}

{% endfor %}
{% for table in item.sharded_tables | default([]) %}
[[sharded_tables]]
database = "{{ table.database }}"
name = "{{ table.name }}"
column = "{{ table.column }}"
data_type = "{{ table.data_type }}"
{% endfor %}
