#SPDX-License-Identifier: MIT-0
---
# handlers file for roles/pgbouncer
- name: Restart pgbouncer
  service:
    name: pgbouncer
    state: restarted

- name: Reload pgbouncer
  service:
    name: pgbouncer
    state: reloaded
