[databases]
{% for db in pgbouncer_databases %}
{{ db.name }} = host={{ db.host }} port={{ db.port }} dbname={{ db.dbname }}
{% endfor %}

[pgbouncer]
listen_port = {{ pgbouncer_listen_port }}
listen_addr = {{ pgbouncer_listen_addr }}
auth_type = {{ pgbouncer_auth_type }}
auth_file = {{ pgbouncer_userlist }}
logfile = {{ pgbouncer_dir }}/pgbouncer.log
pidfile = {{ pgbouncer_dir }}/pgbouncer.pid
# 允许哪些数据库用户连接 PgBouncer 的管理控制台并执行所有管理命令
; 进入 PgBouncer console 后可以执行：
; SHOW POOLS;
; SHOW CLIENTS;
; SHOW SERVERS;
; SHOW CONFIG;
; RELOAD;
; PAUSE;
; RESUME;
; KILL;
; 这些是 管理命令，不是 SQL。
; psql -h 127.0.0.1 -p 5433 -U [postgres/admin] pgbouncer
admin_users = {{ pgbouncer_admin_users }}
; 连接池模式，transaction（事务级，适合高并发）或 session（会话级，适合长连接）
; 注意：如果你需要使用 PostgreSQL 的 LISTEN / NOTIFY 功能，必须将 pool_mode 设置为 session，
; 因为 transaction 模式会在每个事务结束时断开连接，这会导致监听失效。
pool_mode = {{ pgbouncer_pool_mode | default('session') }}
; 最大允许的连接数
max_client_conn = {{ pgbouncer_max_client_conn | default(100) }}
; 默认的连接池尺寸，当使用事务连接池时，20是一个合适的值。对于会话级连接池而言
; 该值是你想在同一时刻处理的最大连接数。
default_pool_size = {{ pgbouncer_default_pool_size | default(20) }}
; 连接池中最少的保留连接数
min_pool_size = 0
; 出现问题时，最多允许多少条额外连接
reserve_pool_size = 10
; 如果客户端等待超过这么多秒，使用备用连接池
reserve_pool_timeout = 5
; 连接在服务器上保持空闲的最大秒数
server_idle_timeout = 60
; 连接在服务器上保持活动的最大秒数，防止长连接堆积
server_lifetime = 3600
; Unix socket 配置
unix_socket_dir = {{ pgbouncer_socket_dir | default('/tmp') }}
unix_socket_mode = {{ pgbouncer_socket_mode | default('0777') }}
unix_socket_group = {{ pgbouncer_socket_group | default('postgres') }}
