---

- name: Install dependencies
  vars:
    _dependencies:
      - rsyslog
      - rsyslog-relp
  apt:
    name: "{{ _dependencies }}"

- name: Ensure rsyslog started
  service:
    name: rsyslog
    state: started
    enabled: yes
