---
ha_mode:            "tcp"   # just tcp
ha_stats_enable:       true
ha_stats_port:         8090
ha_stats_user:         "admin"
ha_stats_password:     "CHANGEME"
ha_proxy_list:
  - ha_listen_port:     8182      # listen
    enable_https:       false     # if true, give ha_ca_name
    ha_ca_dir:          ""        # ../../../misc_files/ca-new
    ha_ca_name:         ""        # .leihuo.netease.com.pem
    ha_backend:
      - { "id": 1, "addr": "127.0.0.1:8181" }
ha_patroni_postgres_list: []
  # - name: pg01
  #   addr: 127.0.0.1:5432 # directly connect to postgres, or through pgbouncer proxy
  # - name: pg02
  #   addr: 127.0.0.1:5433
