---

# Dump pg数据库

# 参数
# HOSTS: 数据库主机列表
# _host: 数据库主机地址/ip，默认_host
# _db: 数据库名称
# _port: 数据库端口，默认5432
# _user: 数据库用户 管理员账号
# _password: 数据库密码
# _pg_dump_dir: 数据库备份目录
# _mode: 备份模式 可选值: sql, dump 默认: sql
# _pg_version: 数据库版本，默认17

# Example:
# ap -e HOSTS=pg-single playbooks/pgdump.yaml -e _mode=sql -e _db=dev -e _user=admin -e _password=admin

- name: Dump pg database
  gather_facts: true
  hosts: "{{ HOSTS }}"
  become: true
  become_user: root
  become_method: sudo
  vars:
    _host: "localhost"
    _port: 5432
    _pg_dump_dir: /srv/dump
    _mode: "sql"
    _pg_version: "17"
  tasks:
    - name: Create dump directory
      file:
        path: "{{ _pg_dump_dir }}"
        state: directory

    - name: Check parameters
      assert:
        that:
          - _host is defined
          - _port is defined
          - _db is defined
          - _user is defined
          - _password is defined
          - _pg_dump_dir is defined
          - _mode is defined
          - _mode in ["sql", "dump"]
          - _port | int > 0 and _port | int < 65536
          - _host is string
          - _db is string
          - _user is string
          - _password is string
          - _pg_dump_dir is string

    - name: Check pg_dump
      shell: command -v pg_dump
      register: _pg_dump
      ignore_errors: true
    - fail:
        msg: "Not find pg_dump, install it"
      when: _pg_dump.rc != 0

    - name: Check connection to database
      shell: |
        export PGPASSWORD="{{ _password }}"
        psql -h {{ _host }} -p {{ _port }} -U {{ _user }} -d {{ _db }} -c "SELECT 1"
      register: _conn
      ignore_errors: true
    - fail:
        msg: "Failed to connect to database {{ _db }}"
      when: _conn.rc != 0

    - name: Fetch current date
      shell: date +"%Y-%m-%d-%H-%M-%S"
      register: _date

    - block:
      - name: Dump pg database {{ _db }} with sql mode with gzip compression
        shell: |
          export PGPASSWORD="{{ _password }}"
          dumpFile="{{ _pg_dump_dir }}/pg-dump-{{ _db }}-{{ _date.stdout }}.sql.gz"
          pg_dump -h {{ _host }} -p {{ _port }} -U {{ _user }} -d {{ _db }} \
          --no-owner --no-privileges | gzip > $dumpFile
          echo $dumpFile
        args:
          executable: /bin/bash
        async: 3600
        poll: 2
        register: _dump_sql
      - name: Dump pg database {{ _db }} with gzip compression
        debug:
          msg: "{{ _dump_sql.stdout }}"
      when: _mode == "sql"

    - block:
      - name: Dump pg database {{ _db }} with dump mode with zlib compression
        shell: |
          export PGPASSWORD="{{ _password }}"
          dumpFile="{{ _pg_dump_dir }}/pg-dump-{{ _db }}-{{ _date.stdout }}.dump"
          pg_dump -h {{ _host }} -p {{ _port }} -U {{ _user }} -d {{ _db }} \
          --no-owner --no-privileges -Fc -Z 9 -f $dumpFile
          echo $dumpFile
        args:
          executable: /bin/bash
        async: 3600
        poll: 2
        register: _dump
      - name: Dump pg database {{ _db }} with zlib compression
        debug:
          msg: "{{ _dump.stdout }}"
      when: _mode == "dump"

    - name: Recovery pg database
      debug:
        msg: |
          # Delete the database {{ _db }} if it exists
          PGPASSWORD='{{ _password }}' psql -h {{ _host }} -p {{ _port }} -U {{ _user }} -d postgres -c "DROP DATABASE IF EXISTS {{ _db }};"

          # Use ansible playbook to initialize database
          ansible-playbook -i hosts.ini playbooks/pg-ha-cluster.yaml -e HOSTS=<pg-cluster-group> -t initdb

          # Restore the dump file with gzip compression
          zcat {{ _pg_dump_dir }}/pg-dump-{{ _db }}-{{ _date.stdout }}.sql.gz | PGPASSWORD='{{ _password }}' psql -h {{ _host }} -p {{ _port }} -U {{ _user }} -d {{ _db }}

          # Restore the dump file with zlib compression (parallel restore with -j flag)
          PGPASSWORD='{{ _password }}' pg_restore -h {{ _host }} -p {{ _port }} -U {{ _user }} -d {{ _db }} -j 4 {{ _pg_dump_dir }}/pg-dump-{{ _db }}-{{ _date.stdout }}.dump
      when: _mode in ["sql", "dump"]
